---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: summit-ecomm-scc-storeuser
  labels:
    backstage.io/kubernetes-id: summit-ecomm
    app.kubernetes.io/name: summit-ecomm
    rht-gitops.com/janus-argocd: summit-ecomm
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 10001
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:summit-ecomm:storeuser-sa
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: summit-ecomm-scc-storeuseradmin
  annotations:
    backstage.io/kubernetes-id: summit-ecomm
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:summit-ecomm:storeuseradmin-sa
